DailyBasket.Warehouse/Areas/Delivery/Models/ViewModels/TripOrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DailyBasket.Warehouse.Areas.Delivery.Models.ViewModels
{
    public class TripOrderViewModel
    {
        public ulong OrderId { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public double OrderAmount { get; set; }
        public string OrderStatus { get; set; }
    }
}

DailyBasket.Warehouse/Areas/Delivery/Models/ViewModels/TripViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DailyBasket.Warehouse.Areas.Delivery.Models.ViewModels
{
    public class TripViewModel
    {
        public ulong TripId { get; set; }
        public string TripDate { get; set; }
        public string DeliveryBoyName { get; set; }
        public string Vehicle { get; set; }
        public double GrandTotal { get; set; }
        public List<TripOrderViewModel> TripOrderList { get; set; }
    }
}

DailyBasket.Warehouse/Areas/Delivery/Controllers/TripController.cs
using DailyBasket.Warehouse.Areas.Delivery.BLL;
using DailyBasket.Warehouse.Areas.Delivery.Models.ViewModels;
using DailyBasket.Warehouse.Areas.Users.BLL;
using DailyBasket.Warehouse.Core.Model.Delivery;
using DailyBasket.Warehouse.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyBasket.Warehouse.Areas.Delivery.Controllers
{
    public class TripController : Controller
    {
        Core.Interface.BLL.Delivery.IDelivery iDelivery;
        public TripController()
        {
            iDelivery = new DeliveryBLL();
        }

        // GET: Delivery/Trip
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CreateTrip()
        {
            BindTripData();
            return View();
        }

        [HttpPost]
        public ActionResult CreateTrip(Trip tripModel)
        {
            if (ModelState.IsValid)
            {
                if (iDelivery.CreateDeliveryTrip(tripModel, SessionManager.CurrentUserId) != 0)
                {
                    TempData["Message"] = "Delivery Trip is created successfully.";
                    TempData["CssClass"] = "text-success";
                    return RedirectToAction("CreateTrip");
                }
                else
                {
                    TempData["Message"] = "Delivery Trip is not created successfully, Please try again!";
                    TempData["CssClass"] = "text-danger";
                }
            }
            BindTripData();
            return View(tripModel);
        }

        private void BindTripData()
        {
            ViewBag.DeliveryBoyDdlList = new UserHandlerBLL().GetWarehouseDeliveryBoyList();
            ViewBag.TripOrderViewModelList = iDelivery.GetOrdersToAssignDeliveryTrip();
        }

        public ActionResult OnHoldDeliveryTrips()
        {
            return View(iDelivery.GetOnHoldDeliveryTrips());
        }

        public ActionResult OnHoldDeliveryTripOrders(ulong tripId = 0)
        {
            if(tripId != 0)
            {
                TripViewModel tripViewModel = iDelivery.GetOnHoldDeliveryTripWithOrders(tripId);
                if (tripViewModel != null)
                    return View(tripViewModel);
            }
            return RedirectToAction("OnHoldDeliveryTrips");
        }

        public ActionResult TripsHistory()
        {
            return View(iDelivery.GetTripsHistory());
        }

        public ActionResult TripHistory(ulong tripId = 0)
        {
            if(tripId != 0)
            {
                TripViewModel tripViewModel = iDelivery.GetTripHistoryWithOrders(tripId);
                if (tripViewModel != null)
                    return View(tripViewModel);
            }
            return RedirectToAction("TripsHistory");
        }
    }
}

DailyBasket.Warehouse/Areas/WebApi/Controllers/VendorController.cs
using DailyBasket.Warehouse.Areas.WebApi.BLL;
using System.Web.Mvc;
using System.Web.Services;

namespace DailyBasket.Warehouse.Areas.WebApi.Controllers
{
    public class VendorController : Controller
    {
        // GET: WebApi/Vendor
        [WebMethod]
        public JsonResult IsVendorNameExists(string vendorName)
        {
            bool status = new VendorBLL().IsVendorNameExists(vendorName);
            return Json(status, JsonRequestBehavior.AllowGet);
        }

        [WebMethod]
        public JsonResult IsVendorEmailIdExists(string vendorEmail)
        {
            bool status = new VendorBLL().IsVendorEmailIdExists(vendorEmail);
            return Json(status, JsonRequestBehavior.AllowGet);
        }

        [WebMethod]
        public JsonResult IsVendorMobileNoExists(string vendorMobile)
        {
            bool status = new VendorBLL().IsVendorMobileNoExists(vendorMobile);
            return Json(status, JsonRequestBehavior.AllowGet);
        }
        
        [WebMethod]
        public JsonResult IsVendorGSTINExists(string gstinumber)
        {
            bool status = new VendorBLL().IsVendorGSTINExists(gstinumber);
            return Json(status, JsonRequestBehavior.AllowGet);
        }
    }
}

DailyBasket.Warehouse/Areas/WebApp/Controllers/OffersController.cs
using DailyBasket.Warehouse.Areas.ProductMaster.BLL;
using DailyBasket.Warehouse.Areas.WebApp.BLL;
using DailyBasket.Warehouse.Core.Interface.BLL.WebApp;
using DailyBasket.Warehouse.Core.Model.DropDownList;
using DailyBasket.Warehouse.Core.Model.WebApp;
using DailyBasket.Warehouse.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyBasket.Warehouse.Areas.WebApp.Controllers
{
    [Authorize(Roles = "Master")]
    public class OffersController : Controller
    {
        IOffer iOffer = new OfferBLL();
        // GET: WebApp/Offers
        public ActionResult Index()
        {
            return RedirectToAction("ActiveOffers");
        }

        [HttpGet]
        public ActionResult AddOffer()
        {
            BindOffersDropDownList();
            return View();
        }

        [HttpPost]
        public ActionResult AddOffer(OfferModel offerModel, HttpPostedFileBase Image)
        {
            if(ModelState.IsValid)
            {
                offerModel.Image = ImageUploadHelper.UploadOfferImage(Image);
                if (iOffer.AddOffer(offerModel, SessionManager.CurrentUserId) != 0)
                {
                    TempData["Message"] = "Offer is added successfully";
                    TempData["CssClass"] = "text-success";
                    return RedirectToAction("AddOffer");
                }
                TempData["Message"] = "Oops error Occured, Please try again!";
                TempData["CssClass"] = "text-danger";
            }
            BindOffersDropDownList();
            return View(offerModel);
        }
        
        public ActionResult ActiveOffers()
        {
            return View(iOffer.GetOfferList(Core.Enum.Status.Active));
        }

        public ActionResult UpdateOfferStatus(uint offerId)
        {
            iOffer.UpdateOfferStatus(offerId, Core.Enum.Status.Inactive, SessionManager.CurrentUserId);
            return RedirectToAction("ActiveOffers");
        }

        private void BindOffersDropDownList()
        {
            ViewBag.OfferTypeDdlList = iOffer.GetOfferTypesDdl();
            ViewBag.SubCategoryList = new ProductCategoryBLL().GetActiveSubCategoryModelList();
        }
    }
}

DailyBasket.Warehouse/Areas/WebApp/Controllers/SliderController.cs
using DailyBasket.Warehouse.Areas.WebApp.BLL;
using DailyBasket.Warehouse.Core.Enum;
using DailyBasket.Warehouse.Core.Model.WebApp;
using DailyBasket.Warehouse.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyBasket.Warehouse.Areas.WebApp.Controllers
{
    public class SliderController : Controller
    {
        // GET: WebApp/Slider
        public ActionResult Index()
        {
            return View();
        }

        Core.Interface.BLL.WebApp.ISlider iSlider;
        public SliderController()
        {
            iSlider = new SliderBLL();
        }
        // GET: WebApp/Slider
        [HttpGet]
        public ActionResult UpdateWebSlider()
        {
            return View(iSlider.GetWebSliderImagesToUpdate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateWebSlider(SliderModel SliderModel, HttpPostedFileBase SliderImage)
        {
            if (ModelState.IsValid)
            {
                SliderModel.SliderImage = ImageUploadHelper.UploadWebSliderImage(SliderImage);
                int status = iSlider.UpdateWebSliderImage(SliderModel, SessionManager.CurrentUserId);
                if (status != 0)
                {
                    ImageUploadHelper.DeleteImage(SliderModel.SliderImagePath);
                    TempData["Message"] = "Slider Image is added successfully";
                    TempData["cssClass"] = "text-success";
                    return RedirectToAction("UpdateWebSlider");
                }
                else
                {
                    TempData["Message"] = "Slider image is not added. Try again.";
                    TempData["cssClass"] = "text-danger";
                }
            }
            return View(iSlider.GetWebSliderImagesToUpdate());
        }

        [HttpGet]
        public ActionResult UpdateAndroidSlider()
        {
            return View(iSlider.GetAndroidSliderImagesToUpdate());
        }

        [HttpPost]
        public ActionResult UpdateAndroidSlider(SliderModel SliderModel, HttpPostedFileBase SliderImage)
        {
            if (ModelState.IsValid)
            {
                SliderModel.SliderImage = ImageUploadHelper.UploadAndroidSliderImage(SliderImage);
                int status = iSlider.UpdateAndroidSliderImage(SliderModel, SessionManager.CurrentUserId);
                if (status != 0)
                {
                    ImageUploadHelper.DeleteImage(SliderModel.SliderImagePath);
                    TempData["Message"] = "Slider Image is added successfully";
                    TempData["cssClass"] = "text-success";
                    return RedirectToAction("UpdateAndroidSlider");
                }
                else
                {
                    TempData["Message"] = "Slider image is not added. Try again.";
                    TempData["cssClass"] = "text-danger";
                }
            }
            return View(iSlider.GetAndroidSliderImagesToUpdate());
        }

        public ActionResult UpdateAndroidSliderStatus(uint sliderId = 0, uint status = 0)
        {
            if(sliderId != 0)
            {
                if(status == (uint)Status.Active)
                    status = (uint)Status.Inactive;
                else
                    status = (uint)Status.Active;
                iSlider.UpdateSliderStatus(sliderId, status, SessionManager.CurrentUserId);
            }
            return RedirectToAction("UpdateAndroidSlider");
        }

        public ActionResult UpdateWebSliderStatus(uint sliderId = 0, uint status = 0)
        {
            if (sliderId != 0)
            {
                if (status == (uint)Status.Active)
                    status = (uint)Status.Inactive;
                else
                    status = (uint)Status.Active;
                iSlider.UpdateSliderStatus(sliderId, status, SessionManager.CurrentUserId);
            }
            return RedirectToAction("UpdateWebSlider");
        }
    }
}

DailyBasket.Warehouse/Areas/WebApp/Controllers/TieupController.cs
using DailyBasket.Warehouse.Areas.WebApp.BLL;
using DailyBasket.Warehouse.Core.Enum;
using DailyBasket.Warehouse.Core.Model.WebApp;
using DailyBasket.Warehouse.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyBasket.Warehouse.Areas.WebApp.Controllers
{
    public class TieupController : Controller
    {
        Core.Interface.BLL.WebApp.ITieup iTieup;
        public TieupController()
        {
            iTieup = new TieupBLL();
        }
        // GET: WebApp/Tieup
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UpdateTieupSlider()
        {
            return View(iTieup.GetTieupImagesToUpdate());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateTieupSlider(TieupModel tieupModel, HttpPostedFileBase TieupImage)
        {
            if (ModelState.IsValid)
            {
                tieupModel.TieupImage = ImageUploadHelper.UploadTieupSliderImage(TieupImage);
                int status = iTieup.UpdateTieupImage(tieupModel, SessionManager.CurrentUserId);
                if (status != 0)
                {
                    ImageUploadHelper.DeleteImage(tieupModel.TieupImagePath);
                    TempData["Message"] = "Tieup Image is added successfully";
                    TempData["cssClass"] = "text-success";
                    return RedirectToAction("UpdateTieupSlider");
                }
                else
                {
                    TempData["Message"] = "Tieup image is not added. Try again.";
                    TempData["cssClass"] = "text-danger";
                }
            }
            return View(iTieup.GetTieupImagesToUpdate());
        }

        public ActionResult UpdateTieupSliderStatus(uint sliderId = 0, uint status = 0)
        {
            if (sliderId != 0)
            {
                if (status == (uint)Status.Active)
                    status = (uint)Status.Inactive;
                else
                    status = (uint)Status.Active;
                iTieup.UpdateTieupStatus(sliderId, status, SessionManager.CurrentUserId);
            }
            return RedirectToAction("UpdateTieupSlider");
        }
    }
}

DailyBasket.Warehouse/Controllers/UserMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyBasket.Warehouse.Controllers
{
    [ChildActionOnly]
    public class UserMenuController : Controller
    {
        // GET: UserMenu
        public ActionResult Master()
        {
            return View("UserMenu/_Master");
        }

        
        public ActionResult Purchase_Manager()
        {
            return View("UserMenu/_PurchaseManager");
        }

        
        public ActionResult Sale_Manager()
        {
            return View("UserMenu/_SaleManager");
        }

        
        public ActionResult Account_Manger()
        {
            return View("UserMenu/_AccountManager");
        }

        
        public ActionResult Delivery()
        {
            return View("UserMenu/_Delivery");
        }

        
        public ActionResult Partner()
        {
            return View("UserMenu/_Partner");
        }

        
        public ActionResult Inverstor()
        {
            return View("UserMenu/_Inverstor");
        }
    }
}

DailyBasket.Warehouse/Views/Shared/UserMenu/_Master.cshtml
<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Users</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Warehouse Users</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("RegisterWarehouseUser", "WarehouseUser", new { Area = "Users" })"><i class="fa fa-circle-o"></i> Register</a></li>
                <li><a href="@Url.Action("WarehouseUserList", "WarehouseUser", new { Area = "Users" })"><i class="fa fa-circle-o"></i> View </a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Online Customers</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("ActiveCustomers", "Customer", new { Area = "Users" })"><i class="fa fa-circle-o"></i> View </a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Franchise Registration</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("RegisterWarehouseFranchise", "WarehouseUser", new { Area = "Users" })"><i class="fa fa-circle-o"></i> Register</a></li>
                <li><a href="@Url.Action("FranchiseeList", "WarehouseUser", new { Area = "Users" })"><i class="fa fa-circle-o"></i> View </a></li>
            </ul>
        </li>
    </ul>
</li>
<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Product Master</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Brand</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("AddBrand", "Brand", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> Add</a></li>
                <li><a href="@Url.Action("BrandList", "Brand", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> View</a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Vendor</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("AddVendor", "Vendor", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> Add</a></li>
                <li><a href="@Url.Action("VendorList", "Vendor", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> View</a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Main Category</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("AddMainCategory", "ProductCategory", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> Add</a></li>
                <li><a href="@Url.Action("MainCategoryList", "ProductCategory", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> View</a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>SubCategory</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("AddSubCategory", "ProductCategory", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> Add</a></li>
                <li><a href="@Url.Action("SubCategoryList", "ProductCategory", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> View</a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Products</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li class="treeview">
                    <a href="@Url.Action("AddProductHsnNumber", "Product", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> Add HSN Number</a>
                    <a href="@Url.Action("AddProduct", "Product", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> Add Product</a>
                    <a href="@Url.Action("ProductList", "Product", new { Area = "ProductMaster" })"><i class="fa fa-circle-o"></i> View</a>
                </li>
            </ul>
        </li>

    </ul>
</li>
<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Purchase Entry</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="@Url.Action("AddPurchaseOrder", "PurchaseOrder", new { Area = "Purchase" })"><i class="fa fa-circle-o"></i> New Entry</a></li>
        <li><a href="@Url.Action("PendingPurchaseEntries", "PurchaseOrder", new { Area = "Purchase" })"><i class="fa fa-circle-o"></i> Pending Entries</a></li>
        <li><a href="@Url.Action("ViewPurchaseOrders", "PurchaseOrder", new { Area = "Purchase" })"><i class="fa fa-circle-o"></i> Purchase History</a></li>
    </ul>
</li>
<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Stock</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="@Url.Action("AvailableStocks", "StockProduct", new { Area = "Stock" })"><i class="fa fa-circle-o"></i> Products Stock</a></li>
        <li><a href="@Url.Action("BatchWiseProductStock", "StockProduct", new { Area = "Stock" })"><i class="fa fa-circle-o"></i> Batchwise Product Stock</a></li>
        <li><a href="@Url.Action("ViewExpiryWiseConvetableProducts", "StockProduct", new { Area = "Stock" })"><i class="fa fa-circle-o"></i> Convertable Products</a></li>
        <li><a href="@Url.Action("ReorderProductsSystem", "StockProduct", new { Area = "Stock" })"><i class="fa fa-circle-o"></i> Reorder System</a></li>
    </ul>
</li>
<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Customer Orders</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="@Url.Action("InProcessOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Pending Orders</a></li>
        <li><a href="@Url.Action("ReadyToDispatchOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Ready to Dispatch</a></li>
        <li><a href="@Url.Action("DispatchedOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Dispatched</a></li>
        <li><a href="@Url.Action("DeliveredOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Delivered</a></li>
        <li><a href="@Url.Action("CancelledOrders", "CustomerOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Cancelled</a></li>
    </ul>
</li>

<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Franchisee Temperary Orders</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="@Url.Action("FranchiseePurchaseOrders", "FranchiseeOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Pending Orders</a></li>
        <li><a href="@Url.Action("FranchiseeOrdersHistory", "FranchiseeOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Order History</a></li>
        <li><a href="@Url.Action("GenerateFranchiseeOrder", "FranchiseeOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Generate Orders</a></li>
    </ul>
</li>

<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Franchisee Orders</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="@Url.Action("InProcessOrders", "FranchiseeOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> In Process Orders</a></li>
        <li><a href="@Url.Action("ReadyToDispatchOrders", "FranchiseeOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Ready to Dispatch</a></li>
        <li><a href="@Url.Action("DispatchedOrders", "FranchiseeOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Dispatched</a></li>
        <li><a href="@Url.Action("DeliveredOrders", "FranchiseeOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Delivered</a></li>
        <li><a href="@Url.Action("CancelledOrders", "FranchiseeOrders", new { Area = "Sale" })"><i class="fa fa-circle-o"></i> Cancelled</a></li>
    </ul>
</li>
<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Delivery</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="@Url.Action("CreateTrip", "Trip", new { Area = "Delivery" })"><i class="fa fa-circle-o"></i> Create Trip</a></li>
        <li><a href="@Url.Action("OnHoldDeliveryTrips", "Trip", new { Area = "Delivery" })"><i class="fa fa-circle-o"></i> View OnHold Trips</a></li>
        <li><a href="@Url.Action("TripsHistory", "Trip", new { Area = "Delivery" })"><i class="fa fa-circle-o"></i> View Trip History</a></li>
    </ul>
</li>
<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Reports</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">

        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Warehouse Reports</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("Purchase", "Purchase", new { Area = "Reports" })"><i class="fa fa-circle-o"></i> Purchase Report</a></li>
                <li><a href="@Url.Action("Sales", "Sale", new { Area = "Reports" })"><i class="fa fa-circle-o"></i> Sales Report</a></li>
                <li><a href="@Url.Action("Stock", "Stock", new { Area = "Reports" })"><i class="fa fa-circle-o"></i> Stock Report</a></li>
            </ul>
        </li>

        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Franchisee Reports</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("FranchiseePurchase", "Purchase", new { Area = "Reports" })"><i class="fa fa-circle-o"></i> Purchase Report</a></li>
                <li><a href="@Url.Action("FranchiseeSales", "Sale", new { Area = "Reports" })"><i class="fa fa-circle-o"></i> Sales Report</a></li>
                <li><a href="@Url.Action("FranchiseeStock", "Stock", new { Area = "Reports" })"><i class="fa fa-circle-o"></i> Stock Report</a></li>
            </ul>
        </li>

    </ul>
</li>
<li class="treeview">
    <a href="#">
        <i class="fa fa-table"></i> <span>Web App</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Sliders</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("UpdateWebSlider", "Slider", new { Area = "WebApp" })"><i class="fa fa-circle-o"></i> Website Slider</a></li>
                <li><a href="@Url.Action("UpdateAndroidSlider", "Slider", new { Area = "WebApp" })"><i class="fa fa-circle-o"></i> Android Slider </a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Offers</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("AddOffer", "Offers", new { Area = "WebApp" })"><i class="fa fa-circle-o"></i> Add New Offer</a></li>
                <li><a href="@Url.Action("ActiveOffers", "Offers", new { Area = "WebApp" })"><i class="fa fa-circle-o"></i> View </a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="@Url.Action("UpdateTieupSlider", "Tieup", new { Area = "WebApp" })">
                <i class="fa fa-table"></i>  <span> Tie Up   </span>
            </a>
        </li>
    </ul>
</li>