DailyBasket.Warehouse/Areas/ProductMaster/Controllers/ProductCategoryController.cs
using DailyBasket.Warehouse.Areas.ProductMaster.BLL;
using DailyBasket.Warehouse.Core.Enum;
using DailyBasket.Warehouse.Core.Model.Product;
using DailyBasket.Warehouse.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyBasket.Warehouse.Areas.ProductMaster.Controllers
{
    [Authorize]
    public class ProductCategoryController : Controller
    {
        ProductCategoryBLL productCategoryBll = new ProductCategoryBLL();
        // GET: ProductMaster/ProductCategory
        public ActionResult Index()
        {
            return RedirectToAction("MainCategoryList");
        }
        
        public ActionResult MainCategoryList()
        {
            return View(productCategoryBll.GetMainCategoryList());
        }
        
        public ActionResult SubCategoryList()
        {
            return View(productCategoryBll.GetSubCategoryList());
        }

        [HttpGet]
        public ActionResult AddMainCategory()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMainCategory(MainCategoryModel mainCategoryModel, HttpPostedFileBase MainCategoryImage)
        {
            if (ModelState.IsValid)
            {
                mainCategoryModel.MainCategoryImage = ImageUploadHelper.UploadMainCategoryImage(MainCategoryImage);
                if (productCategoryBll.AddMainCategory(mainCategoryModel, SessionManager.CurrentUserId) != 0)
                {
                    TempData["Message"] = "Product Main Category is added successfully";
                    TempData["cssClass"] = "text-success";
                    return RedirectToAction("AddMainCategory");
                }
                else
                {
                    TempData["Message"] = "Product Main Category is not added. Try again.";
                    TempData["cssClass"] = "text-danger";
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult AddSubCategory()
        {
            // Get Active Product's Main Category List To Bind Dropdown List
            ViewBag.MainCategoryDdlList = productCategoryBll.GetActiveMainCategoryListDdl();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddSubCategory(SubCategoryModel subCategoryModel, HttpPostedFileBase SubCategoryImage)
        {
            if (ModelState.IsValid)
            {
                subCategoryModel.SubCategoryImage = ImageUploadHelper.UploadSubCategoryImage(SubCategoryImage);
                if (productCategoryBll.AddSubCategory(subCategoryModel, SessionManager.CurrentUserId) != 0)
                {
                    TempData["Message"] = "Product SubCategory is added successfully";
                    TempData["cssClass"] = "text-success";
                    return RedirectToAction("AddSubCategory");
                }
                else
                {
                    TempData["Message"] = "Product SubCategory is not added. Try again.";
                    TempData["cssClass"] = "text-danger";
                }
            }
            ViewBag.MainCategoryDdlList = productCategoryBll.GetActiveMainCategoryListDdl();
            return View();
        }

        [HttpGet]
        public ActionResult UpdateMainCategory(uint mainCatId = 0)
        {
            if(mainCatId != 0)
            {
                MainCategoryModel mainCategoryModel = productCategoryBll.GetMainCategoryToUpdate(mainCatId);
                if (mainCategoryModel != null)
                    return View(mainCategoryModel);
            }
            return RedirectToAction("MainCategoryList");
        }

        [HttpPost]
        public ActionResult UpdateMainCategory(MainCategoryModel mainCategoryModel, string submit, HttpPostedFileBase MainCategoryImage)
        {
            if (ModelState.IsValid)
            {
                switch (submit)
                {
                    case "Update Category":
                        if (productCategoryBll.UpdateMainCategory(mainCategoryModel, SessionManager.CurrentUserId) != 0)
                        {
                            TempData["Message"] = "Main Category is updated successfully.";
                            TempData["CssClass"] = "text-success";
                            return View("UpdateMainCategory", mainCategoryModel);
                        }
                        else
                        {
                            TempData["Message"] = "Opp's occured error! Try again.";
                            TempData["CssClass"] = "text-success";
                            return View("UpdateMainCategory", mainCategoryModel);
                        }
                    case "Update Image":
                        mainCategoryModel.MainCategoryImage = ImageUploadHelper.UploadMainCategoryImage(MainCategoryImage);
                        if(mainCategoryModel.MainCategoryImage != null)
                        {
                            string oldMCImage = productCategoryBll.GetMainCategoryImageToDelete(mainCategoryModel.MainCategoryId);
                            if (productCategoryBll.UpdateMainCategory(mainCategoryModel, SessionManager.CurrentUserId) != 0)
                            {
                                ImageUploadHelper.DeleteImage(oldMCImage);
                                TempData["Message"] = "Main Category Image is uploaded successfully.";
                                TempData["CssClass"] = "text-success";
                                TempData["McImageView"] = "displayMCImageView";
                                return View("UpdateMainCategory", mainCategoryModel);
                            }
                        }
                        TempData["McImageView"] = "displayMCImageView";
                        TempData["Message"] = "Opp's occured error! Try again.";
                        TempData["CssClass"] = "text-success";
                        return View("UpdateMainCategory", mainCategoryModel);
                    default:
                        return RedirectToAction("MainCategoryList");
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult UpdateSubCategory(uint subCatId = 0)
        {
            if (subCatId != 0)
            {
                SubCategoryModel subCategoryModel = productCategoryBll.GetSubCategoryToUpdate(subCatId);
                if (subCategoryModel != null)
                    return View(subCategoryModel);
            }
            return RedirectToAction("SubCategoryList");
        }

        [HttpPost]
        public ActionResult UpdateSubCategory(SubCategoryModel subCategoryModel, string submit, HttpPostedFileBase SubCategoryImage)
        {
            if (ModelState.IsValid)
            {
                switch (submit)
                {
                    case "Update SubCategory":
                        if (productCategoryBll.UpdateSubCategory(subCategoryModel, SessionManager.CurrentUserId) != 0)
                        {
                            TempData["Message"] = "SubCategory is updated successfully.";
                            TempData["CssClass"] = "text-success";
                            return View("UpdateSubCategory", subCategoryModel);
                        }
                        else
                        {
                            TempData["Message"] = "Opp's occured error! Try again.";
                            TempData["CssClass"] = "text-danger";
                            return View("UpdateSubCategory", subCategoryModel);
                        }
                    case "Update SubCategory Image":
                        subCategoryModel.SubCategoryImage = ImageUploadHelper.UploadSubCategoryImage(SubCategoryImage);
                        if (subCategoryModel.SubCategoryImage != null)
                        {
                            string oldMCImage = productCategoryBll.GetSubCategoryImageToDelete(subCategoryModel.SubCategoryId);
                            if (productCategoryBll.UpdateSubCategory(subCategoryModel, SessionManager.CurrentUserId) != 0)
                            {
                                ImageUploadHelper.DeleteImage(oldMCImage);
                                TempData["Message"] = "SubCategory Image is uploaded successfully.";
                                TempData["CssClass"] = "text-success";
                                TempData["ScImageView"] = "displaySCImageView";
                                return View("UpdateSubCategory", subCategoryModel);
                            }
                        }
                        TempData["ScImageView"] = "displaySCImageView";
                        TempData["Message"] = "Opp's occured error! Try again.";
                        TempData["CssClass"] = "text-danger";
                        return View("UpdateSubCategory", subCategoryModel);
                    default:
                        return RedirectToAction("SubCategoryList");
                }
            }
            return View();
        }

        public ActionResult UpdateMainCategoryStatus(uint mainCatId = 0, uint status = 0)
        {
            if (mainCatId != 0)
            {
                if (status == (uint)Status.Active)
                    status = (uint)Status.Inactive;
                else
                    status = (uint)Status.Active;
                productCategoryBll.UpdateMainCategoryStatus(mainCatId, status, SessionManager.CurrentUserId);
            }
            return RedirectToAction("MainCategoryList");
        }

        public ActionResult UpdateSubCategoryStatus(uint subCatId = 0, uint status = 0)
        {
            if (subCatId != 0)
            {
                if (status == (uint)Status.Active)
                    status = (uint)Status.Inactive;

DailyBasket.Warehouse/Areas/ProductMaster/Views/ProductCategory/AddMainCategory.cshtml
@model DailyBasket.Warehouse.Core.Model.Product.MainCategoryModel
@{
    ViewBag.Title = "Add Product Main Category";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<section class="content-header text-center "><h1>Add Product Category</h1></section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-offset-3 col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                @if(TempData["Message"] != null)
                {
                    <div class="col-lg-12 text-center">
                        <label class="@TempData["CssClass"].ToString()">@TempData["Message"].ToString()</label>
                    </div>
                }
                <!-- form start -->
                @using (Html.BeginForm("AddMainCategory", "ProductCategory", FormMethod.Post, htmlAttributes: new { @enctype = "multipart/form-data", @onsubmit = "return validateMainCategoryForm();" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.MainCategoryName, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.MainCategoryName, new { htmlAttributes = new { @class = "form-control", @reqduired = "true", @placeholder = "Product Category Name", @onblur = "validateMainCategory();", @onkeyup = "removeValidationMessage(this.id);" } })
                            @Html.ValidationMessageFor(model => model.MainCategoryName, "", new { @class = "text-danger" })

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MainCategoryImage, htmlAttributes: new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.MainCategoryImage, new { type = "file", @class = "form-control", @required = true, @onchange = "validateProductCategoryImage(this)" })
                            @Html.ValidationMessageFor(model => model.MainCategoryImage, "", new { @class = "text-danger" })

                        </div>

                        <div class="box-footer">

                            <input type="submit" value="Submit" class="btn btn-primary"/>
                            <input type="reset" value="Reset" class="btn btn-warning"/>
                        </div>
                    </div>
                }
            </div>
            <!-- /.box -->
        </div>
    </div>
    <!-- /.row -->
</section>
@Scripts.Render("~/bundles/script/async/product-master/product-maincat-form")
@Scripts.Render("~/bundles/script/async/product-master/pcategory-image-validation")

DailyBasket.Warehouse/Areas/ProductMaster/Views/ProductCategory/AddSubCategory.cshtml
@model DailyBasket.Warehouse.Core.Model.Product.SubCategoryModel
@{
    ViewBag.Title = "Add Product SubCategory";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header text-center "><h1>Add Product Sub Category</h1></section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-offset-3 col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                @if (TempData["Message"] != null)
                {
                    <div class="col-lg-12 text-center">
                        <label class="@TempData["CssClass"].ToString()">@TempData["Message"].ToString()</label>
                    </div>
                }
                <!-- form start -->
                @using (Html.BeginForm("AddSubCategory", "ProductCategory", FormMethod.Post, htmlAttributes: new { @enctype = "multipart/form-data", @onsubmit = "return validateSubCategoryForm();" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="box-body">
                        <div class="form-group">
                            @Html.Label("Main Category", htmlAttributes: new { @class = "control-label" })
                            @Html.TextBox("SelectMainCategoryId", null, htmlAttributes: new { @class = "form-control", @required = true, @placeholder = "Select Main Category" })
                            @Html.DropDownListFor(model => model.MainCategoryId, ViewBag.MainCategoryDdlList != null ? ViewBag.MainCategoryDdlList as SelectList : Enumerable.Empty<SelectListItem>(), "Select Main Category", htmlAttributes: new { @class = "form-control hide-form-field", @required = true })

                            @Html.ValidationMessageFor(model => model.MainCategoryId, "", new { @class = "text-danger" })
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.SubCategoryName, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.SubCategoryName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Sub Category", @required = "true", @onblur = "validateSubCategory();", @onkeyup = "removeValidationMessage(this.id);" } })
                            @Html.ValidationMessageFor(model => model.SubCategoryName, "", new { @class = "text-danger" })

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.SubCategoryImage, htmlAttributes: new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.SubCategoryImage, new { type = "file", @class = "form-control", @required = true, @onchange = "validateProductCategoryImage(this)" })
                            @Html.ValidationMessageFor(model => model.SubCategoryImage, "", new { @class = "text-danger" })

                        </div>


                        <div class="form-group">

                            <input type="submit" value="Submit" class="btn btn-primary" />
                            <input type="reset" value="Reset" class="btn btn-warning" />

                        </div>
                    </div>
                }
            </div>
            <!-- /.box -->
        </div>
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
@Scripts.Render("~/bundles/script/async/product-master/product-subcat-form")

<script>
    var jsonMCList = null;
    var autoPopulateMCList = new Array();

    $(document).ready(function () {

        jsonMCList = @Html.Raw(Json.Encode(@ViewBag.MainCategoryDdlList));
        $(jsonMCList).each(function(index, MainCategory){
            autoPopulateMCList.push(MainCategory.Text);
        });

        $("#SelectMainCategoryId").autocomplete({
            source: autoPopulateMCList,

            change: function (event, ui) {
                if (!ui.item) {
                    this.value = '';
                    $('#MainCategoryId option:selected').removeAttr('selected');
                    $("#MainCategoryId option[value='']").attr("selected", true);
                }
                else
                {
                    var id = "";
                    $(jsonMCList).each(function(index, MainCategory){
                        if(MainCategory.Text==ui.item.value){
                            id = MainCategory.Value;
                        }
                    });
                    $('#MainCategoryId option:selected').removeAttr('selected');
                    $("#MainCategoryId option[value='"+id+"']").attr("selected", true);
                }
            }
        });
    });
</script>

DailyBasket.Warehouse/Areas/ProductMaster/Views/ProductCategory/MainCategoryList.cshtml
@model IEnumerable<DailyBasket.Warehouse.Core.Model.Product.MainCategoryModel>
@using DailyBasket.Warehouse.Core.Enum;
@{
    ViewBag.Title = "Product Main Categories";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<section class="content-header">
    <div class="col-sm-10 col-xs-12 text-center">
        <h1>
            Product Main Categories
        </h1>
    </div>
    <div class="col-sm-2 col-xs-12">
        <h1>
            @Html.ActionLink("Add Main Category", "AddMainCategory", "ProductCategory", new { Area = "ProductMaster" }, new { @class = "btn btn-info pull-right" })
        </h1>
    </div>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Sr. No</th>
                                <th>Product Main Category</th>
                                <th>Status</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Any())
                            {
                                var index = 1;
                                foreach (var mainCategory in Model)
                                {

                                    <tr>
                                        <td>@(index++)</td>
                                        <td>@mainCategory.MainCategoryName</td>
                                        <td>@(mainCategory.Status == (uint)Status.Active ? "Active" : "Inactive")</td>

                                        <td class="text-center fontset">
                                            <a href="@Url.Action("UpdateMainCategory", "ProductCategory", new { Area = "ProductMaster", @mainCatId = mainCategory.MainCategoryId })" class="fa fa-edit btn-xs btn-warning" title="Update"></a>
                                            <a href="@Url.Action("UpdateMainCategoryStatus", "ProductCategory", new { Area = "ProductMaster", @mainCatId = mainCategory.MainCategoryId, @status = mainCategory.Status })" class="fa fa-power-off btn-xs btn-warning" title="Change Status"></a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="4"><label class="text-danger">No Record Found</label></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

DailyBasket.Warehouse/Areas/ProductMaster/Views/ProductCategory/SubCategoryList.cshtml
@model IEnumerable<DailyBasket.Warehouse.Core.Model.Product.SubCategoryModel>
@using DailyBasket.Warehouse.Core.Enum;
@{
    ViewBag.Title = "Product SubCategories";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<section class="content-header">
    <div class="col-sm-10 col-xs-12 text-center">
        <h1>
            Product SubCategories
        </h1>
    </div>
    <div class="col-sm-2 col-xs-12">
        <h1>
            @Html.ActionLink("Add Product SubCategory", "AddSubCategory", "ProductCategory", new { Area = "ProductMaster" }, new { @class = "btn btn-info pull-right" })
        </h1>
    </div>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Sr. No</th>
                                <th>Main Category</th>
                                <th>Sub Category</th>
                                <th>Status</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Any())
                            {
                                var index = 1;
                                foreach (var subCategory in Model)
                                {

                                    <tr>
                                        <td>@(index++)</td>
                                        <td>@subCategory.MainCategory</td>
                                        <td>@subCategory.SubCategoryName</td>
                                        <td>@(subCategory.Status == (uint)Status.Active ? "Active" : "Inactive")</td>

                                        <td class="text-center fontset">
                                            <a href="@Url.Action("UpdateSubCategory", "ProductCategory", new { Area = "ProductMaster", @subCatId = subCategory.SubCategoryId })" class="fa fa-edit btn-xs btn-warning" title="Update"></a>
                                            <a href="@Url.Action("UpdateSubCategoryStatus", "ProductCategory", new { Area = "ProductMaster", @subCatId = subCategory.SubCategoryId, @status = subCategory.Status })" class="fa fa-power-off btn-xs btn-warning" title="Change Status"></a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="4"><label class="text-danger">No Record Found</label></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

DailyBasket.Warehouse/Areas/ProductMaster/Views/ProductCategory/UpdateMainCategory.cshtml
@model DailyBasket.Warehouse.Core.Model.Product.MainCategoryModel
@{
    ViewBag.Title = "Update Product Main Category";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<section class="content-header text-center "><h1>Update Product Main Category</h1></section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-offset-3 col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                @if (TempData["Message"] != null)
                {
                    <div class="col-lg-12 text-center">
                        <label class="@TempData["CssClass"].ToString()">@TempData["Message"].ToString()</label>
                    </div>
                }
                <!-- form start -->

                <div class="tab">
                    <a class="tablinks active" onclick="openTab(event, 'tab1')" @(TempData["McImageView"] == null ? "id=defaultOpen" : "")>Category Name</a>
                    <a class="tablinks" onclick="openTab(event, 'tab2')" @(TempData["McImageView"] != null ? "id=defaultOpen" : "")>Category Image</a>
                </div>
                <div class="box-body">
                    @using (Html.BeginForm("UpdateMainCategory", "ProductCategory", FormMethod.Post, htmlAttributes: new { @enctype = "multipart/form-data", @onsubmit = "return validateMainCategoryUpdateName();" }))
                    {
                        @Html.AntiForgeryToken()
                        <div id="tab1" class="tabcontent">
                            <div class="form-group">
                                @Html.HiddenFor(model => model.MainCategoryId)
                                @Html.LabelFor(model => model.MainCategoryName, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.MainCategoryName, new { htmlAttributes = new { @class = "form-control", @reqduired = "true", @placeholder = "Product Category Name", @onblur = "validateMainCategory();", @onkeyup = "removeValidationMessage(this.id);" } })
                                @Html.ValidationMessageFor(model => model.MainCategoryName, "", new { @class = "text-danger" })
                            </div>
                            <div class="box-footer">
                                <input type="submit" name="submit" value="Update Category" class="btn btn-primary" />
                                <a href="@Url.Action("MainCategoryList", "ProductCategory")" class="btn btn-warning">Cancel</a>
                            </div>
                        </div>
                    }
                    @using (Html.BeginForm("UpdateMainCategory", "ProductCategory", FormMethod.Post, htmlAttributes: new { @enctype = "multipart/form-data", @onsubmit = "return validateMainCategoryUpdateImage();" }))
                    {
                        @Html.AntiForgeryToken()
                        <div id="tab2" class="tabcontent">
                            <div class="form-group">
                                @Html.LabelFor(model => model.MainCategoryName, htmlAttributes: new { @class = "control-label" })
                                @Html.TextBox("DisplayMCN", Model.MainCategoryName, new { @class = "form-control", @disabled = "true", @Value = Model.MainCategoryName })
                            </div>
                            
                                <div class="form-group">
                                    @Html.HiddenFor(model => model.MainCategoryId)
                                    @Html.HiddenFor(model => model.MainCategoryName)
                                    @Html.LabelFor(model => model.MainCategoryImage, htmlAttributes: new { @class = "control-label" })
                                    @Html.TextBoxFor(model => model.MainCategoryImage, new { type = "file", @class = "form-control", @required = true, @onchange = "validateProductCategoryImage(this)" })
                                    @Html.ValidationMessageFor(model => model.MainCategoryImage, "", new { @class = "text-danger" })
                                </div>
                                <div class="box-footer">
                                    <input type="submit" name="submit" value="Update Image" class="btn btn-primary" />
                                    <a href="@Url.Action("MainCategoryList", "ProductCategory")" class="btn btn-warning">Cancel</a>
                                </div>
                            </div>
                    }
                </div>

            </div>
            <!-- /.box -->
        </div>
    </div>
    <!-- /.row -->
</section>
@Scripts.Render("~/bundles/script/async/product-master/product-maincat-form")
@Scripts.Render("~/bundles/script/async/product-master/pcategory-image-validation")
@Scripts.Render("~/bundles/script/tab-switch-script")