DailyBasket.Warehouse/Areas/ProductMaster/Controllers/BrandController.cs
using DailyBasket.Warehouse.Areas.ProductMaster.BLL;
using DailyBasket.Warehouse.Core.Model.Product;
using DailyBasket.Warehouse.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyBasket.Warehouse.Areas.ProductMaster.Controllers
{
    [Authorize]
    public class BrandController : Controller
    {
        BrandBLL brandBLL = new BrandBLL();
        // GET: ProductMaster/Brand
        public ActionResult Index()
        {
            return RedirectToAction("BrandList");
        }

        public ActionResult BrandList()
        {
            return View(brandBLL.GetBrandList());
        }

        [HttpGet]
        public ActionResult AddBrand()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBrand(BrandModel brandModel, HttpPostedFileBase BrandImage)
        {
            if (ModelState.IsValid)
            {
                brandModel.BrandImage = ImageUploadHelper.UploadBrandImage(BrandImage);
                if (brandBLL.AddBrand(brandModel, SessionManager.CurrentUserId) != 0)
                {
                    TempData["Message"] = "Brand is added successfully...";
                    TempData["CssClass"] = "text-success";
                    return RedirectToAction("AddBrand");
                }
                else
                {
                    TempData["Message"] = "Brand is not added successfully, Please try again!";
                    TempData["CssClass"] = "text-danger";
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult UpdateBrand(uint brandId = 0)
        {
            if (brandId != 0)
            {
                BrandModel brandModel = brandBLL.GetBrandToUpdate(brandId);
                if (brandModel != null)
                {
                    return View(brandModel);
                }
            }
            return RedirectToAction("BrandList");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateBrand(BrandModel brandModel, string submit, HttpPostedFileBase BrandImage)
        {
            if (ModelState.IsValid)
            {
                switch (submit)
                {
                    case "Update Brand":
                        if (brandBLL.UpdateBrand(brandModel, SessionManager.CurrentUserId) != 0)
                        {
                            return RedirectToAction("BrandList");
                        }
                        else
                        {
                            TempData["Message"] = "Brand is not added successfully, Please try again!";
                            TempData["CssClass"] = "text-danger";
                            return View(brandModel);
                        }
                    case "Update Image":
                        brandModel.BrandImage = ImageUploadHelper.UploadBrandImage(BrandImage);
                        if (brandModel.BrandImage != null)
                        {
                            string oldBrandImage = brandBLL.GetBrandImageToDelete(brandModel.Id);
                            if (brandBLL.UpdateBrand(brandModel, SessionManager.CurrentUserId) != 0)
                            {
                                ImageUploadHelper.DeleteImage(oldBrandImage);
                                TempData["Message"] = "Brand Image is uploaded successfully.";
                                TempData["CssClass"] = "text-success";
                                TempData["BImageView"] = "displayBImageView";
                                return View(brandModel);
                            }
                        }
                        TempData["BImageView"] = "displayBImageView";
                        TempData["Message"] = "Opp's occured error! Try again.";
                        TempData["CssClass"] = "text-danger";
                        return View(brandModel);
                    default:
                        return RedirectToAction("BrandList");
                }
            }
            return View();
        }
    }
}

DailyBasket.Warehouse/Areas/ProductMaster/Views/Brand/AddBrand.cshtml
@model DailyBasket.Warehouse.Core.Model.Product.BrandModel
@{
    ViewBag.Title = "Add Brand";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<section class="content-header text-center"><h1>Add Brand</h1></section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-offset-3 col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                @if (TempData["Message"] != null)
                {
                    <div class="col-lg-12 text-center">
                        <label class="@TempData["CssClass"].ToString()">@TempData["Message"].ToString()</label>
                    </div>
                }
                <!-- form start -->
                @using (Html.BeginForm("AddBrand", "Brand", FormMethod.Post, htmlAttributes: new { @enctype = "multipart/form-data", @onsubmit = "return validateBrandForm();" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })

                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Brand Name", @required = true, @onkeyup = "removeValidationMessage(this.id);" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.BrandImage, htmlAttributes: new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.BrandImage, new { type = "file", @class = "form-control", @required = true, @onchange = "validateProductBrandImage(this)" })
                            @Html.ValidationMessageFor(model => model.BrandImage, "", new { @class = "text-danger" })

                        </div>

                        <div class="box-footer">
                            <input type="submit" value="Submit" class="btn btn-primary" />
                            <input type="reset" value="Reset" class="btn btn-warning" />
                        </div>
                    </div>
                }
            </div>
            <!-- /.box -->
        </div>
    </div>
    <!-- /.row -->
</section>
@Scripts.Render("~/bundles/script/async/product-master/brand-form-validation")
@Scripts.Render("~/bundles/script/async/product-master/pbrand-image-validation")

DailyBasket.Warehouse/Areas/ProductMaster/Views/Brand/BrandList.cshtml
@model IEnumerable<DailyBasket.Warehouse.Core.Model.Product.BrandModel>
@{
    ViewBag.Title = "Brands";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<section class="content-header">
    <div class="col-sm-10 col-xs-12 text-center">
        <h1>
            Brand List
        </h1>
    </div>
    <div class="col-sm-2 col-xs-12">
        <h1>
            @Html.ActionLink("Add Brand", "AddBrand", "Brand", new { Area = "ProductMaster" }, new { @class = "btn btn-info pull-right" })
        </h1>
</div>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Sr.No.</th>
                                <th>Brand Name</th>
                                <th>Status</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Any())
                            {
                                var index = 1;
                                foreach (var brand in Model)
                                {

                                    <tr>
                                        <td>@(index++)</td>
                                        <td>@brand.Name</td>
                                        <td>@(brand.Status != 0 ? "Active" : "Inactive")</td>
     
                                        <td class="text-center fontset">
                                             <a href="@Url.Action("UpdateBrand", "Brand", new { Area = "ProductMaster", @brandId = brand.Id })" class="fa fa-edit btn-xs btn-warning" title="Update"></a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="4"><label class="text-danger">No Record Found</label></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

DailyBasket.Warehouse/Areas/ProductMaster/Views/Brand/UpdateBrand.cshtml
@model DailyBasket.Warehouse.Core.Model.Product.BrandModel
@{
    ViewBag.Title = "Update Brand";
    Layout = "~/Views/Shared/_DailyBasketLayout.cshtml";
}

<section class="content-header text-center"><h1>Update Brand</h1></section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-offset-3 col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                @if (TempData["Message"] != null)
                {
                    <div class="col-lg-12 text-center">
                        <label class="@TempData["CssClass"].ToString()">@TempData["Message"].ToString()</label>
                    </div>
                }
                <div class="tab">
                    <a class="tablinks active" onclick="openTab(event, 'tab1')" @(TempData["BImageView"] == null ? "id=defaultOpen" : "")>Brand Name</a>
                    <a class="tablinks" onclick="openTab(event, 'tab2')" @(TempData["BImageView"] != null ? "id=defaultOpen" : "")>Brand Image</a>
                </div>
                <!-- form start -->
                <div class="box-body">
                    @using (Html.BeginForm("UpdateBrand", "Brand", FormMethod.Post, htmlAttributes: new { @enctype = "multipart/form-data", @onsubmit = "return validateBrandUpdateName();" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.Id)
                        <div id="tab1" class="tabcontent">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Brand Name", @required = true, @onkeyup = "removeValidationMessage(this.id);" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                            </div>
                            <div class="box-footer">
                                <input type="submit" name="submit" value="Update Brand" class="btn btn-primary" />
                                <a href="@Url.Action("BrandList", "Brand", new { @Area = "ProductMaster" })" class="btn btn-warning">Cancel</a>
                            </div>
                        </div>
                    }
                    @using (Html.BeginForm("UpdateBrand", "Brand", FormMethod.Post, htmlAttributes: new { @enctype = "multipart/form-data", @onsubmit = "return validateBrandUpdateImage();" }))
                    {
                        @Html.AntiForgeryToken()
                        <div id="tab2" class="tabcontent">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                                @Html.TextBox("DisplayBN", Model.Name, new { @class = "form-control", @disabled = "true", @Value = Model.Name })

                            </div>
                            <div class="form-group">
                                @Html.HiddenFor(model => model.Id)
                                @Html.HiddenFor(model => model.Name)
                                @Html.LabelFor(model => model.BrandImage, htmlAttributes: new { @class = "control-label" })
                                @Html.TextBoxFor(model => model.BrandImage, new { type = "file", @class = "form-control", @required = true, @onchange = "validateProductBrandImage(this)" })
                                @Html.ValidationMessageFor(model => model.BrandImage, "", new { @class = "text-danger" })
                            </div>
                            <div class="box-footer">
                                <input type="submit" name="submit" value="Update Image" class="btn btn-primary" />
                                <a href="@Url.Action("BrandList", "Brand", new { @Area = "ProductMaster" })" class="btn btn-warning">Cancel</a>
                            </div>
                        </div>
                    }
                </div>

            </div>
            <!-- /.box -->
        </div>
    </div>
    <!-- /.row -->
</section>
@Scripts.Render("~/bundles/script/async/product-master/brand-form-validation")
@Scripts.Render("~/bundles/script/async/product-master/pbrand-image-validation")
@Scripts.Render("~/bundles/script/tab-switch-script")